@baseUrl = http://localhost:3333

# Health check 
GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "teste",
    "description": "sala de teste"
}

###

    @roomId = {{createRoom.response.body.$.roomId}}

###

# Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Room
# @name createQuestion
POST {{baseUrl}}/rooms/86f4ea87-e045-4445-ad56-447396d8cb69/questions
Accept: application/json
Content-Type: application/json

{
    "question": "O que é VueJS e a sua diferença entre React?"
}
